print('Multiplicação * ', 10 * 10)
print('Adição + ', 10 + 10)
print('Subtração - ', 10 - 5)
print('Divisão / ', 10 / 5)
print('Divisão inteira // ', 10 // 3)
print('Potenciação ** ', 2 ** 10)
print('Módulo (resto da divisão) % ', 10 % 3)
print('Alterar a precedência () ', (5+2)*10)
print(10 * 'Brunno')

